services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: EventHubDb
    ports:
      - "5433:5432"

  eventhub.api:
    image: eventhub.api
    build:
      context: .
      dockerfile: EventHub.Api/Dockerfile
    ports:
      - "8000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=EventHubDb;Username=postgres;Password=YourSecurePassword123!
    depends_on:
      - db

  eventhub.web:
    image: eventhub.web
    build:
      context: .
      dockerfile: EventHub.Web/Dockerfile
    ports:
      - "8001:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    depends_on:
      - eventhub.api